### ISSUE TITLE
problem with bdpy package

### ISSUE THREAD

**Issue by ghost** [KamitaniLab/GenericObjectDecoding#10]
Hey, I am trying to use this file with python 2.7.12. However, it seems like that the package provided named bdpy doesn't work well with your .mat document.

**Comment by ShuntaroAoki** [comment]
Thanks for reporting.
Could you tell me:
- which file caused the error?
- the error message you got?

**Comment by ghost** [comment]
1. analysis_FeaturePrediction.py
2.NotImplementedError: Please use HDF reader for matlab v7.3 files
python2.7/site-packages/bdpy/bdata/bdata.py

**Comment by ShuntaroAoki** [comment]
The error was due to file format changes in our lab. I've updated the public data files at figshare and Python code in this repository to the latest version, so please re-try it.
