### ISSUE TITLE
Regarding Createfigure.py

### ISSUE THREAD

**Issue by NidhiSultan** [KamitaniLab/GenericObjectDecoding#11]
Hi 
while running createfigure.py no result is coming out. Also it doesn't even plot any value is it because of some python version or something?

**Comment by ShuntaroAoki** [comment]
Hi,
did the script give you any error messages? If so, could you tell me the outputs?

**Comment by NidhiSultan** [comment]
Hi, 
It's resolved now. 
Thanks for asking.
