### ISSUE TITLE
About ImageFeature file

### ISSUE THREAD

**Issue by mina98** [KamitaniLab/GenericObjectDecoding#13]
i want to ask about more details for image feature file , how it's shape is (16234,) but the stimulus photos  are only 1250 image

**Comment by mitsuaki** [comment]
In addition to the features for 1250 images, we included category-averaged features for 15,372 categories in ImageNet (See "Category-average feature decoding" subsection in Horikawa and Kamitani (2017), https://www.nature.com/articles/ncomms15037 ).
So, totally we have 16622 image feature vectors in the image feature file (ImageFeature.h5). If not, the file may be broken.

**Comment by mina98** [comment]
okay thanks, can i get the images, stimulus and visual images? because some of this photo deleted on imagenet @mitsuaki

**Comment by mina98** [comment]
Thanks for helping
