### ISSUE TITLE
warning and operand error

### ISSUE THREAD

**Issue by mithuna123** [KamitaniLab/GenericObjectDecoding#16]
i got an warning error in analysis feature prediction merge results file.it is not a problem but the code was interrupted in subject2 cnn8.i have attached the screenshot(error.png)
![error](https://user-images.githubusercontent.com/66509066/83938323-e093e580-a7f0-11ea-887f-16300303a069.png)

**Comment by mitsuaki** [comment]
Hi @mithuna123 , 
Sorry for late response.

It seems that loading prediction results ended after ...-Subject2-v2-cnn8.pkl was loaded.
The analysis_FeaturePredictionMergeResults.py script loads all pkl files in ./results/GenericObjectDecoding/ directory.
So please check if there are pkl files for all subjects (subject1-5), ROIs (V1, .., VC), and CNN layers (cnn1-8) in the ./results/* directory.

The pkl files in the ./reuslts/* directory are created when you run the analysis_FeaturePrediction.py script. 
If something is missing, please rerun the analysis_FeaturePrediction.py.
( before rerunning, please remove all files in ./tmp/ directory if exist )

**Comment by mithuna123** [comment]
thank you sir.i will try sir
