### ISSUE TITLE
Training Session Image Representation

### ISSUE THREAD

**Issue by kubrakyuz** [KamitaniLab/GenericObjectDecoding#18]
Hi,
I use your dataset in my thesis. I'm confused about one thing. You wrote in the training session that each image is presented once, but shouldn't we accept it as showing 5 pictures twice in each run? In other words, for instance is it correct to consider fMRI signals as twice generated for the 456th index image?
![image](https://user-images.githubusercontent.com/55322267/94995739-fc45a780-05a8-11eb-8628-acbc37c3e7e3.PNG)
![experimental](https://user-images.githubusercontent.com/55322267/94995752-0ff10e00-05a9-11eb-8078-6e8a1845ac17.PNG)

**Comment by ShuntaroAoki** [comment]
Hi,

Right. As you found out, we presented five randomly selected images twice in successive trials within each run (in your screenshot, image n3079230_8270, index 456). And the subject was asked to press a button when the same image was successively presented across trials. This is so-called one-back repetition task. We introduced the task to keep subject's attention on the stimuli and to ensure the subject is looking at the stimuli.

In our analysis, we excluded fMRI signals in the one-back repetition trials (in your screenshot, trial 7).
