### ISSUE TITLE
Finding all 1200 and 50 train and test images

### ISSUE THREAD

**Issue by MalihaUCF** [KamitaniLab/GenericObjectDecoding#21]
Hi @mitsuaki , I am having trouble finding all the train and test images.  I used the URL links and downloaded the images from the internet directly. The total images are however not 1200 now as many links were broken and some images were also corrupt. I have in total 838 images for training and testing. If possible, could you please share all the training and test images or the images_112.npz file ? It would help me a lot. 

also, I discovered, that since my images are < 1200 , I might incur problem with the corresponding fMRI matlab files. Please advise. Thanks

**Comment by mitsuaki** [comment]
Hi @MalihaUCF,
Sorry, the request form for stimulus images is opened at https://forms.gle/ujvA34948Xg49jdn9
Please send a request from above link.

**Comment by MalihaUCF** [comment]
Great! Just found them, thank you !! :)
