### ISSUE TITLE
Why does the length of data in 'ROI_VC' is different in two files?

### ISSUE THREAD

**Issue by dlmdlmacy** [KamitaniLab/GenericObjectDecoding#24]
Hello! Firstly, thank you for your excellent work! I have one question about the dataset.

I downloaded the data at [figshare](https://figshare.com/articles/dataset/Generic_Object_Decoding/7387130?file=25103408). There are two kinds of files: **Subject1.h5** and **Subject1_ImageNetTraining/ImageNetTest/Imagery.h5** (take subject1 for example). I use bdpy to select 'ROI_VC' data, but the length is 4466 and 3444 respectively. Why does this happen? Is this because one was using SPM to preprocess and the other was using fMRIPrep?

Thank you!

**Comment by ShuntaroAoki** [comment]
Yes, the difference is due to different preprocessing. SPM was used in the original study (Horikawa & Kamitani, 2017), and recently we switched our lab's preprocessing pipeline to fmriprep. We confirmed that the results were well consistent between SPM and fmriprep in our in-house study.

**Comment by dlmdlmacy** [comment]
Thanks a lot for your help! I'll close this issue.
