### ISSUE TITLE
where is “fmri_Subject1_VC.pkl”

### ISSUE THREAD

**Issue by zhangbaijin** [KamitaniLab/GenericObjectDecoding#25]
Hi，thanks for your share，i have a problem where is fmri_Subject1_VC.pkl

**Comment by ShuntaroAoki** [comment]
We didn't share fMRI data as pkl files with such naming.
Preprocessed fMRI data are shared at fighsare as 'Subject1.h5'.
https://github.com/KamitaniLab/GenericObjectDecoding/blob/master/data/README.md
