### ISSUE TITLE
Stimulas images

### ISSUE THREAD

**Issue by wenyu427** [KamitaniLab/GenericObjectDecoding#26]
Dear all
Can you share stimulus images dataset with me? 
I can't download all the images from the experiment.Thank you.
Best regards

**Comment by ShuntaroAoki** [comment]
Please send us a request for the stimulus images via <https://forms.gle/ujvA34948Xg49jdn9>.
Then we'll send you download link for a zip file of the stimulus images.

**Comment by wenyu427** [comment]
I have received stimulus images, thank you very much!
