### ISSUE TITLE
Will brainliner.jp be accessed normally soon?

### ISSUE THREAD

**Issue by dlmdlmacy** [KamitaniLab/GenericObjectDecoding#28]
Hello!

Thank you for your excellent job! I'm doing a research using the .mat data on http://brainliner.jp/data/brainliner/Generic_Object_Decoding . However, when I tried to access this website, I got a 502 error. So I really want to know that will this website return to normal soon? Or it stops service?

Thank you for your replies! Have a good day!

Yours,
dlmdlmacy

**Comment by ShuntaroAoki** [comment]
I apologise for the inconvenience. Now I'm working with admins to fix the issue.

BTW, data used in the Generic Object Decoding paper are also available at figshare (https://figshare.com/articles/dataset/Generic_Object_Decoding/7387130). The following files are same as those released on Brainliner.
- fMRI data: Subject1.mat, Subject2.mat, Subject3.mat, Subject4.mat, Subject5.mat
- Image features: ImageFeatures.mat

**Comment by ShuntaroAoki** [comment]
We've fixed the issue on brainliner.jp. Now you can access and download the data.

**Comment by dlmdlmacy** [comment]
Thank you SOOOOOOOOOOOOOOOOOOO much! It can be accessed normally.
