### ISSUE TITLE
Get labels for the images

### ISSUE THREAD

**Issue by qihongl** [KamitaniLab/GenericObjectDecoding#4]
This might be a silly question... how do I map the downloaded images to the [labels](https://gist.github.com/yrevar/942d3a0ac09ec9e5eb3a)?

**Comment by ShuntaroAoki** [comment]
Downloaded images are named as 'n01518878_10042.JPEG'. The first part in the file name (e.g., 'n01518878') is WordNet/ImageNet synset ID. Our code or dataset do not include mappings between the synset IDs and human-readable labels. You can find them at ImageNet (http://image-net.org/explore) or WordNet (https://wordnet.princeton.edu/wordnet/download/current-version/).

**Comment by qihongl** [comment]
I see! Thank you very much! This is super helpful!
