### ISSUE TITLE
Get stimuli presentation order (for the brain data)?

### ISSUE THREAD

**Issue by qihongl** [KamitaniLab/GenericObjectDecoding#5]
Is there a simple way of getting which stimulus (image) was presented at which time point? I guess it is stored somewhere? 

I apologize if this is an obvious question... but I'm not familiar with the package you are using. Or do you have documentation about how to use the [brain decoding toolbox ](https://github.com/KamitaniLab/BrainDecoderToolbox2) somewhere? 

Thanks in advance!

**Comment by ShuntaroAoki** [comment]
In MATLAB, the following code will give you a N x 1 matrix (`labels`) in which each row is an image ID for each sample (by using our BrainDecoderToolbox2). The image ID is an float number based on image file name (e.g., `1518878.010042` indicates `n01518878_10042.JPEG`).

```matlab
[dataSet, metaData] = load_data('Subject1.mat');
labels = get_dataset(dataSet, metaData, 'Label');
```

Currently, the toolbox is not well documented yet. So, feel free to ask any question about it.

**Comment by qihongl** [comment]
I see! Thanks a lot! I really appreciate it!

**Comment by qihongl** [comment]
By the way, thank you very much for releasing this very interesting dataset!
