### ISSUE TITLE
num voxels of the data mismatch with config?

### ISSUE THREAD

**Issue by qihongl** [KamitaniLab/GenericObjectDecoding#6]
I just have another quick question: 
Is this the correct way of extracting brain data from a particular ROI? If I run the following code, by checking the shape of X, the number of voxels in 'HVC' is 2049. However, according to the `config` file, `num_voxel['HVC']` is 1000. Am I misunderstanding something? 

```
import bdpy
import numpy as np 

subjects = config.subjects
rois = config.rois
num_voxel = config.num_voxel

sbj = 'Subject1'
roi = 'HVC'

data = bdpy.BData(subjects[sbj][0])
X = data.select(rois[roi])
print(np.shape(X)) 
print(num_voxel[roi])
```

Thank you very much in advance!

**Comment by ShuntaroAoki** [comment]
`num_voxel` in the config is the number of voxels selected for prediction analysis, not the number of voxels included in ROIs. In the analysis, we selected voxels showing the highest correlation with the target variable (visual features) in the training image sessions (500 voxels for V1-V4, LOC, and FFA, PPA; 1000 for LVC, HVC, and VC; please see 'ROI selection' in the original paper).

**Comment by qihongl** [comment]
I see! Thank you very much!
