### ISSUE TITLE
question：It shows error   “Undefined function or variable 'repadd’” while trying analysis_FeaturePrediction.m

### ISSUE THREAD

**Issue by miyucka** [KamitaniLab/GenericObjectDecoding#9]
I am trying to run a Generic Decoding Demo program.
It shows error “Undefined function or variable 'repadd’” while trying analysis_FeaturePrediction.m
I searched for “reaped.m” in GenericObjectDecoding folder and BrainDecoderToolbox2 folder, 
but I couldn’t find it. (I found “reaped.c” instead.)
Any suggestions on how to fix error? 
Appreciate your help.

**Comment by ShuntaroAoki** [comment]
The function `repadd` is included in lib/mex_prog_2010-06-21 as a mex program. So please check and try the followings:

1. Make sure lib/mex_prog_2010-06-21 is included in your Matlab path,
2. Try re-building repadd (as well as the other mex functions) on your Matlab.

**Comment by miyucka** [comment]
Thank you for your reply. 
The problem was solved when I followed your advice.
I did not know I needed to build “reaped.c”. 
Thank you very much.

**Comment by miyucka** [comment]
question：
I’m sorry to bother you, but I have another question about “analysis_FeaturePrediction.m”
It shows error “Error using weight_out_delay_time” and “Requested 7516192768001x1750 (98000000.0GB) array exceeds maximum array size preference. ~” when I try analysis_FeaturePrediction.m
Is this a normal state? （I feel the data size is too big…）
If this is normal, could you tell me system requirements?
Thank you for your support.

**Comment by ShuntaroAoki** [comment]
The demo script, analysis_FeaturePrediction.m, is designed for prediction of relatively small number of units (e.g., 1000 for each layer) and it doesn't support something like prediction of all units in DNNs. When we handle such large data, we divide the units into sub groups and run the prediction for each group to avoid memory error. We are going to add such practical code in future. Sorry for the inconvenience.
